# Generated by Django 4.2.8 on 2025-07-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_cart_remove_order_books_order_status_orderitem_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="price_at_purchase",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
