# Generated by Django 4.2.8 on 2025-07-15 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("bio", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(default="")),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "type",
                    models.CharField(
                        choices=[("ebook", "E-book"), ("audiobook", "Audiobook")],
                        default="",
                        max_length=10,
                    ),
                ),
                ("cover_image", models.ImageField(default="", upload_to="covers/")),
                ("file", models.FileField(default="", upload_to="books/")),
                (
                    "audio_sample",
                    models.FileField(blank=True, null=True, upload_to="samples/"),
                ),
                ("published_at", models.DateField(default="")),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.author",
                    ),
                ),
                ("categories", models.ManyToManyField(to="store.category")),
            ],
        ),
    ]
