# Generated by Django 4.2.8 on 2025-07-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="file",
            field=models.FileField(
                blank=True, default="", null=True, upload_to="books/"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="published_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="type",
            field=models.CharField(
                choices=[("ebook", "E-book"), ("audiobook", "Audiobook")],
                default="ebook",
                max_length=10,
            ),
        ),
    ]
