# Generated by Django 4.2.8 on 2025-07-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_book_file_alter_book_published_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
