# Generated by Django 4.2.8 on 2025-07-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_book_description_alter_book_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
    ]
